version: "3"

networks:
  common:
    driver: bridge

volumes:
  data-volume:

services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=openers
      - MONGO_INITDB_ROOT_USERNAME=tvhelp
      - MONGO_INITDB_ROOT_PASSWORD=tvhelp
    volumes:
      - data-volume:/data/db
      - ./mongo_init_script:/docker-entrypoint-initdb.d
    ports:
      - "0.0.0.0:27017-27019:27017-27019"
    networks:
      - common
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:1.33
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    networks:
      - common
    restart: always      

  backend:
    build:
      context: ../../
      dockerfile: ./deployment/compose/Dockerfile-debug
    environment:
      - DATABASE_URL=mongodb://openers:Q123456q@mongodb:27017/admin?authSource=openers
      - JWT_SECRET_KEY=sgfjlksdjfwer9qfndlknfkljsdfh
      - MODE=development
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined  
    ports:
      - "8081:4000"
      - "8765:8765"
    volumes:
      - ../../:/app
      - /openers/dist:/openers/dist
    networks:
      - common
    depends_on:
      - mongodb
      - jaeger
    restart: always
